spring.application.name=calmanchor-api
# Server configuration
server.port=8081

# Firebase Admin SDK service account
firebase.credentials.path=classpath:calmanchor-1177d-firebase-adminsdk-fbsvc-b416922f0d.json

# Logging (optional)
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG
